[package]
name = "openshell"
version = "0.1.0"
authors = ["707 <707472783@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.8.1"
ansi_term = "0.12"
clap = "2.33.1"
rustyline = "6.2.0"